### ISSUE TITLE
Search Page Improvements

### ISSUE THREAD

**Issue by mjakeman** [mjakeman/extension-manager#33]
A catch-all issue for some improvements to the search page:
 - [X] **Do not search on start up:** Currently the application queries extensions.gnome.org for a search on startup regardless of whether the user is on the Browse page or not. Change this to run only when the browse page is loaded. This will require a rework of the main GUI. (#35)
 - [X] **Add search progress indicator:** When search is happening in the background, display a progress indicator (spinner) so the user is aware the application is still responsive. (#36)
 - [x] **Show screenshots and extension icons (#3):** Make searching more useful by displaying screenshots. These should be loaded "on-demand", either when the entry is expanded, or by moving search results to a separate page (i.e. like GNOME Software).
 - [x] **Support filtering search results:** Allow switching between "Top" and "New" (other categories are probably not relevant)
 - [x] **Display shell version map:** Show all supported versions of GNOME Shell
 - [x] **Show reviews (#4):** Show the review score of the extension and somehow display text reviews
 - [x] **Type to search:** Initiate a search when the user starts typing. Alternatively, grab focus for the search bar by default. (#137)
